<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Contexts">
  <eClassifiers xsi:type="ecore:EClass" name="Variable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variableID" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="v_context" lowerBound="1"
        eType="#//AnalysisContext" containment="true" eOpposite="#//AnalysisContext/c_variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnalysisContext">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contextID" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="c_variable" lowerBound="1"
        eType="#//Variable" eOpposite="#//Variable/v_context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="behavior" lowerBound="1"
        upperBound="-1" eType="#//WorkloadBehavior" containment="true" eOpposite="#//WorkloadBehavior/behaviorInContext"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="platform" lowerBound="1"
        upperBound="-1" eType="#//ResourcePlatform" containment="true" eOpposite="#//ResourcePlatform/platformInContext"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourcePlatform">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="platformID" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="platformInContext" lowerBound="1"
        eType="#//AnalysisContext" eOpposite="#//AnalysisContext/platform"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkloadBehavior">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="behaviorID" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="behaviorInContext" lowerBound="1"
        eType="#//AnalysisContext" eOpposite="#//AnalysisContext/behavior"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="demand" lowerBound="1"
        upperBound="-1" eType="#//WorkloadEvent" containment="true" eOpposite="#//WorkloadEvent/eventInBehavior"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkloadEvent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eventID" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventInBehavior" lowerBound="1"
        eType="#//WorkloadBehavior" eOpposite="#//WorkloadBehavior/demand"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generator" eType="#//WorkloadGenerator"
        eOpposite="#//WorkloadGenerator/generatorInEvent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trace" eType="#//EventTrace"
        eOpposite="#//EventTrace/traceInEvent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkloadGenerator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generatorID" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatorInEvent" lowerBound="1"
        eType="#//WorkloadEvent" eOpposite="#//WorkloadEvent/generator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventTrace">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="traceID" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traceInEvent" lowerBound="1"
        eType="#//WorkloadEvent" eOpposite="#//WorkloadEvent/trace"/>
  </eClassifiers>
</ecore:EPackage>
