<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="xYArru" nsURI="http://www.example.org/xYArru" nsPrefix="xYArru">
  <eClassifiers xsi:type="ecore:EDataType" name="NewDataType1" instanceTypeName="newDataType1"/>
  <eClassifiers xsi:type="ecore:EClass"/>
  <eClassifiers xsi:type="ecore:EEnum" name="NewEnum1"/>
  <eClassifiers xsi:type="ecore:EDataType" name="NewDataType3" instanceTypeName="newDataType3"/>
  <eSubpackages name="newPackage1"/>
  <eSubpackages name="GRM/ResourceTypes">
    <eClassifiers xsi:type="ecore:EClass" name="Resource" eSuperTypes="#//%">
      <eOperations name="resMult"/>
      <eOperations name="isProtected"/>
      <eOperations name="isActive"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SynchResource" eSuperTypes="#//GRM%2FResourceTypes/Resource"/>
    <eClassifiers xsi:type="ecore:EClass" name="StorageResource" eSuperTypes="#//GRM%2FResourceTypes/Resource"/>
    <eClassifiers xsi:type="ecore:EClass" name="CommunicationResource" eSuperTypes="#//GRM%2FResourceTypes/Resource"/>
    <eClassifiers xsi:type="ecore:EClass" name="DeviceResource" eSuperTypes="#//GRM%2FResourceTypes/Resource"/>
    <eClassifiers xsi:type="ecore:EClass" name="ConcurrencyResource" eSuperTypes="#//GRM%2FResourceTypes/Resource"/>
    <eClassifiers xsi:type="ecore:EClass" name="ComputingResource" eSuperTypes="#//GRM%2FResourceTypes/Resource"/>
    <eClassifiers xsi:type="ecore:EClass" name="TimingResource" eSuperTypes="#//GRM%2FResourceTypes/Resource">
      <eStructuralFeatures xsi:type="ecore:EReference" name="neweclass13" eType="#//GRM%2FResourceTypes/ResourceService"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CommunicationEndPoint" eSuperTypes="#//GRM%2FResourceTypes/CommunicationResource">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="packetSize" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Integer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CommunicationMedia" eSuperTypes="#//GRM%2FResourceTypes/CommunicationResource">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementSize" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="packetTime" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Duration"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="blockingTime" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Duration"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="transmMode" eType="#//GRM%2FResourceTypes/TransmModeKind"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="TransmModeKind" instanceTypeName="TransmModeKind"/>
    <eClassifiers xsi:type="ecore:EClass" name="ClockResource" eSuperTypes="#//GRM%2FResourceTypes/TimingResource"/>
    <eClassifiers xsi:type="ecore:EClass" name="TimerResource" eSuperTypes="#//GRM%2FResourceTypes/TimingResource">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Duration" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Duration"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isProtected" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResourceService"/>
  </eSubpackages>
  <eSubpackages name="ResourceManagement">
    <eClassifiers xsi:type="ecore:EClass" name="Resource"/>
    <eClassifiers xsi:type="ecore:EClass" name="ResourceBroker" eSuperTypes="#//ResourceManagement/Resource">
      <eStructuralFeatures xsi:type="ecore:EReference" name="BrokedResource" lowerBound="1"
          upperBound="-1" eType="#//ResourceManagement/Resource"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="accesscotrolpolicy" lowerBound="1"
          upperBound="-1" eType="#//ResourceManagement/AccessCotrolPolicy" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResourceManager" eSuperTypes="#//ResourceManagement/Resource">
      <eStructuralFeatures xsi:type="ecore:EReference" name="resource" lowerBound="1"
          upperBound="-1" eType="#//ResourceManagement/Resource" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resourcecontrolpolicy"
          lowerBound="1" upperBound="-1" eType="#//ResourceManagement/ResourceControlPolicy"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AccessCotrolPolicy"/>
    <eClassifiers xsi:type="ecore:EClass" name="ResourceControlPolicy"/>
  </eSubpackages>
  <eSubpackages name="ResourceCore">
    <eClassifiers xsi:type="ecore:EClass" name="Instance">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          upperBound="-1" eType="#//ResourceCore/Classfier" eOpposite="#//ResourceCore/Classfier/instance"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Classfier">
      <eStructuralFeatures xsi:type="ecore:EReference" name="instance" upperBound="-1"
          eType="#//ResourceCore/Instance" eOpposite="#//ResourceCore/Instance/type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResourceInstance" eSuperTypes="#//ResourceCore/Instance">
      <eStructuralFeatures xsi:type="ecore:EReference" name="exeServices" lowerBound="1"
          upperBound="-1" eType="#//ResourceCore/ResourceServiceExecution" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resource" eType="#//ResourceCore/Resource"
          eOpposite="#//ResourceCore/Resource/resourceinstance"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Resource" eSuperTypes="#//ResourceCore/BhavioredClassfier">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="resMult" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="pServices" upperBound="-1"
          eType="#//ResourceCore/ResourceServices" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resourceinstance" eType="#//ResourceCore/ResourceInstance"
          eOpposite="#//ResourceCore/ResourceInstance/resource"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BhavioredClassfier" eSuperTypes="#//ResourceCore/Classfier">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownbehavior" upperBound="-1"
          eType="#//ResourceCore/Behavior" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BehaviorExecution"/>
    <eClassifiers xsi:type="ecore:EClass" name="ResourceServiceExecution" eSuperTypes="#//ResourceCore/BehaviorExecution">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//ResourceCore/ResourceServices"
          eOpposite="#//ResourceCore/ResourceServices/instance"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResourceServices" eSuperTypes="#//ResourceCore/Behavior">
      <eStructuralFeatures xsi:type="ecore:EReference" name="instance" eType="#//ResourceCore/ResourceServiceExecution"
          eOpposite="#//ResourceCore/ResourceServiceExecution/type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Behavior"/>
  </eSubpackages>
  <eSubpackages name="Scheduling">
    <eClassifiers xsi:type="ecore:EEnum" name="SchedPolicyKind">
      <eLiterals name="EarliestDeadlineFirst"/>
      <eLiterals name="FIFO" value="1"/>
      <eLiterals name="FixedPriority" value="2"/>
      <eLiterals name="LeastLaxityFirst" value="3"/>
      <eLiterals name="RoundRobin" value="4"/>
      <eLiterals name="TimetableDriven" value="5"/>
      <eLiterals name="Undef" value="6"/>
      <eLiterals name="Other" value="7"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResourceBroker">
      <eStructuralFeatures xsi:type="ecore:EReference" name="resource" eType="#//Scheduling/Resource"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="accesscontrolpolicy"
          upperBound="-1" eType="#//Scheduling/AccessControlPolicy" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AccessControlPolicy"/>
    <eClassifiers xsi:type="ecore:EClass" name="Resource"/>
    <eClassifiers xsi:type="ecore:EClass" name="ProcessingResource" eSuperTypes="#//Scheduling/Resource">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="speedFactor" lowerBound="1"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Float"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Scheduler" eSuperTypes="#//Scheduling/ResourceBroker">
      <eStructuralFeatures xsi:type="ecore:EReference" name="schedulingpolicy" upperBound="-1"
          eType="#//Scheduling/SchedulingPolicy" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="schedulableresource"
          eType="#//Scheduling/SchedulableResource" eOpposite="#//Scheduling/SchedulableResource/scheduler"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="schedule" eType="#//Scheduling/ScheduleSpecification"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SchedulingPolicy" eSuperTypes="#//Scheduling/AccessControlPolicy">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="policy" eType="#//Scheduling/SchedPolicyKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="otherSchedPolicy" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SecondaryScheduler" eSuperTypes="#//Scheduling/Scheduler">
      <eStructuralFeatures xsi:type="ecore:EReference" name="schedulableresource"
          eType="#//Scheduling/SchedulableResource" eOpposite="#//Scheduling/SchedulableResource/secondaryscheduler"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConcurrencyResource"/>
    <eClassifiers xsi:type="ecore:EClass" name="SchedulableResource" eSuperTypes="#//Scheduling/ConcurrencyResource">
      <eStructuralFeatures xsi:type="ecore:EReference" name="schedulingparameters"
          upperBound="-1" eType="#//Scheduling/SchedulingParameters" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="secondaryscheduler" eType="#//Scheduling/SecondaryScheduler"
          eOpposite="#//Scheduling/SecondaryScheduler/schedulableresource"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="scheduler" eType="#//Scheduling/Scheduler"
          eOpposite="#//Scheduling/Scheduler/schedulableresource"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SchedulingParameters"/>
    <eClassifiers xsi:type="ecore:EClass" name="ComputingResource" eSuperTypes="#//Scheduling/ProcessingResource"/>
    <eClassifiers xsi:type="ecore:EClass" name="DeviceResource" eSuperTypes="#//Scheduling/ProcessingResource"/>
    <eClassifiers xsi:type="ecore:EClass" name="CommunicationMedia" eSuperTypes="#//Scheduling/ProcessingResource"/>
    <eClassifiers xsi:type="ecore:EDataType" name="ScheduleSpecification" instanceTypeName="newDataType2"/>
  </eSubpackages>
  <eSubpackages name="ResourceUsages">
    <eClassifiers xsi:type="ecore:EClass" name="Event"/>
    <eClassifiers xsi:type="ecore:EClass" name="Resource"/>
    <eClassifiers xsi:type="ecore:EClass" name="Resource"/>
    <eClassifiers xsi:type="ecore:EClass" name="UsageDemand">
      <eStructuralFeatures xsi:type="ecore:EReference" name="neweclass5" eType="#//ResourceUsages/NewEClass5"
          eOpposite="#//ResourceUsages/NewEClass5/neweclass4"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="neweclass1" eType="#//ResourceUsages/Event"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NewEClass5">
      <eStructuralFeatures xsi:type="ecore:EReference" name="neweclass9" upperBound="-1"
          eType="#//ResourceUsages/UsageTypeAmount" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="neweclass4" eType="#//ResourceUsages/UsageDemand"
          eOpposite="#//ResourceUsages/UsageDemand/neweclass5"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="neweclass2" eType="#//ResourceUsages/Resource"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StaticUsage" eSuperTypes="#//ResourceUsages/NewEClass5"/>
    <eClassifiers xsi:type="ecore:EClass" name="StaticUsage" eSuperTypes="#//ResourceUsages/DeviceResource #//ResourceUsages/NewEClass5"/>
    <eClassifiers xsi:type="ecore:EClass" name="DeviceResource"/>
    <eClassifiers xsi:type="ecore:EClass" name="UsageTypeAmount" eSuperTypes="#//ResourceUsages/Resource.1">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="execTime" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Duration"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="msgSize" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="allocatedMemory" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="usedMemory" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="powerPeak" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Float"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="energy" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Float"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
