<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="HRM" nsURI="yangzhiru" nsPrefix="yangzhiru">
  <eClassifiers xsi:type="ecore:EClass" name="Resource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HW_ComputingResource" eSuperTypes="#//HwResource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hw_processor" lowerBound="1"
        upperBound="-1" eType="#//HW_Processor" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HW_Bus" eSuperTypes="#//HW_CommunicationResource"/>
  <eClassifiers xsi:type="ecore:EClass" name="HW_Memory" eSuperTypes="#//HwResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="addr" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HW_CommunicationResource" eSuperTypes="#//HwResource"/>
  <eClassifiers xsi:type="ecore:EClass" name="HwResource" eSuperTypes="#//Resource"/>
  <eClassifiers xsi:type="ecore:EClass" name="HW_Bridge" eSuperTypes="#//HW_CommunicationResource"/>
  <eClassifiers xsi:type="ecore:EClass" name="HW_Processor"/>
  <eClassifiers xsi:type="ecore:EClass" name="HW_Clock" eSuperTypes="#//HwResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="freq" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
