<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="SRM" nsURI="yangzhiru" nsPrefix="yangzhiru">
  <eClassifiers xsi:type="ecore:EClass" name="SW_CommunicationResource" eSuperTypes="#//SW_Resource"/>
  <eClassifiers xsi:type="ecore:EClass" name="SW_ComputingResource" eSuperTypes="#//SW_Resource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="freq" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeslice" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MemoryPartition" eSuperTypes="#//SW_Resource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="addr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InterruptResource" eSuperTypes="#//SW_Resource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="desc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SW_Resource" eSuperTypes="#//Resource"/>
  <eClassifiers xsi:type="ecore:EClass" name="SW_Channel" eSuperTypes="#//SW_CommunicationResource"/>
  <eClassifiers xsi:type="ecore:EClass" name="SW_Piple" eSuperTypes="#//SW_CommunicationResource"/>
  <eClassifiers xsi:type="ecore:EClass" name="Process">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="preferProcessor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="memorypartition" lowerBound="1"
        eType="#//MemoryPartition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sw_computingresource" lowerBound="1"
        eType="#//SW_ComputingResource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sw_communicationresource"
        upperBound="-1" eType="#//SW_CommunicationResource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interruptresource" eType="#//InterruptResource"/>
  </eClassifiers>
</ecore:EPackage>
