<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dRM" nsURI="http://www.example.org/dRM" nsPrefix="dRM">
  <eSubpackages name="Brokering">
    <eClassifiers xsi:type="ecore:EClass" name="SwResource"/>
    <eClassifiers xsi:type="ecore:EClass" name="DeviceBroker" eSuperTypes="#//Brokering/SwResource">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessPolicy" eType="#//Brokering/AccessPolicyKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isBuffered" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="devices" upperBound="-1"
          eType="#//Brokering/TypedElement"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="closeServices" eType="#//Brokering/BehavioralFeature"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="controlServices" eType="#//Brokering/BehavioralFeature"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="openServices" eType="#//Brokering/BehavioralFeature"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="readServices" eType="#//Brokering/BehavioralFeature"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="writeServices" eType="#//Brokering/BehavioralFeature"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="AccessPolicyKind">
      <eLiterals name="Read"/>
      <eLiterals name="Write" value="1"/>
      <eLiterals name="ReadWrite" value="2"/>
      <eLiterals name="Undef" value="3"/>
      <eLiterals name="Other" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MemoryBroker" eSuperTypes="#//Brokering/SwResource">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessPolicy" eType="#//Brokering/AccessPolicyKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="memories" eType="#//Brokering/TypedElement"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="memoryBlockAddressElements"
          eType="#//Brokering/TypedElement"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="memoryBlockSizeElements"
          eType="#//Brokering/TypedElement"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lockServices" eType="#//Brokering/BehavioralFeature"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="unlockServices" eType="#//Brokering/BehavioralFeature"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mapServices" eType="#//Brokering/BehavioralFeature"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="unMapServices" eType="#//Brokering/BehavioralFeature"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="TypedElement" instanceTypeName="newDataType2"/>
    <eClassifiers xsi:type="ecore:EDataType" name="BehavioralFeature" instanceTypeName="newDataType3"/>
  </eSubpackages>
  <eSubpackages name="Concurrency">
    <eClassifiers xsi:type="ecore:EClass" name="Allocate"/>
    <eClassifiers xsi:type="ecore:EClass" name="SwResource"/>
    <eClassifiers xsi:type="ecore:EClass" name="NewEClass3"/>
    <eClassifiers xsi:type="ecore:EClass" name="EntryPoint" eSuperTypes="#//Concurrency/Allocate">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isReentrant" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="routine" eType="#//Brokering/BehavioralFeature"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="InterruptKind">
      <eLiterals name="HardwareInterruption"/>
      <eLiterals name="ProcessorDetectedException" value="1"/>
      <eLiterals name="ProgrammedException" value="2"/>
      <eLiterals name="Undef" value="3"/>
      <eLiterals name="Other" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SwConcurrentResource" eSuperTypes="#//Concurrency/SwResource">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//Brokering/TypedElement"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="activationCapacity" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="entryPoints" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="addressSpace" eType="#//Brokering/TypedElement"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="periodElements" eType="#//Brokering/TypedElement"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="priorityElements" eType="#//Brokering/TypedElement"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="heapSizeElements" eType="#//Brokering/TypedElement"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="stackSizeElement" eType="#//Brokering/TypedElement"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="activateServices" eType="#//Brokering/BehavioralFeature"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enableConcurrencyServices"
          eType="#//Brokering/BehavioralFeature"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="resumeServices" eType="#//Brokering/BehavioralFeature"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="suspendServices" eType="#//Brokering/BehavioralFeature"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="terminateServices" eType="#//Brokering/BehavioralFeature"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ScheduableResource"/>
    <eClassifiers xsi:type="ecore:EClass" name="InterruptResource" eSuperTypes="#//Concurrency/SwConcurrentResource">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//Concurrency/InterruptKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMaskable" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="vectorElements" eType="#//Brokering/TypedElement"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maskElements" eType="#//Brokering/TypedElement"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="routineConnectServices"
          eType="#//Brokering/BehavioralFeature"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="routineDisconnectServices"
          eType="#//Brokering/BehavioralFeature"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SwSchedualbeResource" eSuperTypes="#//Concurrency/ScheduableResource #//Concurrency/SwConcurrentResource">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isStaticSchedulingFeature"
          eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPreemptable" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="scheduler" eType="#//Brokering/TypedElement"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="deadlineElements" eType="#//Brokering/TypedElement"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="deadlineTypeElements"
          eType="#//Brokering/TypedElement"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeSliceElements" eType="#//Brokering/TypedElement"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="delayServices" eType="#//Brokering/BehavioralFeature"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="joinServices" eType="#//Brokering/BehavioralFeature"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="yieldServices" eType="#//Brokering/BehavioralFeature"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Alarm" eSuperTypes="#//Concurrency/InterruptResource">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isWatching" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="timers" eType="#//Brokering/TypedElement"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SwResource"/>
    <eClassifiers xsi:type="ecore:EClass" name="NameSpace"/>
    <eClassifiers xsi:type="ecore:EClass" name="MemoryPartition" eSuperTypes="#//Concurrency/SwResource.1">
      <eStructuralFeatures xsi:type="ecore:EReference" name="namespace" eType="#//Concurrency/NameSpace"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="concurrentResources"
          eType="#//Brokering/TypedElement"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="memorySpaces" eType="#//Brokering/TypedElement"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fork" eType="#//Brokering/BehavioralFeature"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="exit" eType="#//Brokering/BehavioralFeature"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TimerResource"/>
    <eClassifiers xsi:type="ecore:EClass" name="SwTimerResource" eSuperTypes="#//Concurrency/TimerResource">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="durationElements" eType="#//Brokering/TypedElement"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="Resource">
    <eClassifiers xsi:type="ecore:EClass" name="Resource">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxRIS" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="neweclass5" upperBound="-1"
          eType="#//Resource/ResourceService" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResourceManager" eSuperTypes="#//Resource/Resource"/>
    <eClassifiers xsi:type="ecore:EClass" name="SwResource" eSuperTypes="#//Resource/ResourceManager">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifierElements" eType="#//Resource/ModelElement.1"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="stateElements" eType="#//Resource/ModelElement.1"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="memorySizeFootprint"
          eType="#//Resource/ModelElement.1"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="services" upperBound="-1"
          eType="#//Resource/ResourceServices"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResourceServices"/>
    <eClassifiers xsi:type="ecore:EClass" name="ResourceService">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
          eType="#//Resource/Parameter" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ModelElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//Resource/ModelElement"/>
    <eClassifiers xsi:type="ecore:EDataType" name="ModelElement" instanceTypeName="newDataType1"/>
  </eSubpackages>
  <eSubpackages name="Interaction">
    <eClassifiers xsi:type="ecore:EClass" name="SwResource"/>
    <eClassifiers xsi:type="ecore:EClass" name="ResourceBroker"/>
    <eClassifiers xsi:type="ecore:EClass" name="CommunicationEndPoint"/>
    <eClassifiers xsi:type="ecore:EClass" name="SwInteractionResource" eSuperTypes="#//Interaction/SwResource #//Interaction/ResourceBroker #//Interaction/CommunicationEndPoint">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isIntraMemoryPartitionalinteraction"
          eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="waitingQueuePolicy" eType="#//Interaction/QueuePolicyKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="waitingQueueCapacity"
          eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="waitingPolicyElements"
          eType="#//Resource/ModelElement.1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SwCommunicationResource" eSuperTypes="#//Interaction/SwInteractionResource"/>
    <eClassifiers xsi:type="ecore:EClass" name="SwSynchronizationResource" eSuperTypes="#//Interaction/SwInteractionResource"/>
    <eClassifiers xsi:type="ecore:EEnum" name="QueuePolicyKind">
      <eLiterals name="FIFO"/>
      <eLiterals name="FILO" value="1"/>
      <eLiterals name="Priority" value="2"/>
      <eLiterals name="Undef" value="3"/>
      <eLiterals name="Other" value="4"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
